Repository jupyter/terminado, pull requests merged in 2021-08, with the labels that each got.

#111 Switch select() to poll() in pty_read()
  terminado/management.py
Labels: bug

#112 Log terminal output
  terminado/websocket.py
Labels: enhancement

#114 Clean up tests
  .github/workflows/test.yml
  terminado/tests/basic_test.py
Labels: maintenance

#115 Update Changelog for 0.11.1 Release
  CHANGELOG.md
Labels: documentation

#116 Replace deprecated unittest aliases
  terminado/tests/basic_test.py
Labels: maintenance
