Repository jupyter/terminado, pull requests merged in 2021-05, with the labels that each got.

#102 avoid persistent handle on IOLoop instance
  terminado/management.py
Labels: bug

#103 async/await syntax
  terminado/management.py
  terminado/tests/basic_test.py
Labels: maintenance

#104 Support creating terminal given name in kwargs.
  terminado/management.py
Labels: enhancement

#105 Update changelog for 0.10.0
  CHANGELOG.md
Labels: documentation
