Repository jupyter/terminado, pull requests merged in 2022-03, with the labels that each got.

#142 Add test for terminating the terminals
  .github/workflows/check-release.yml
  .github/workflows/test.yml
  terminado/management.py
  terminado/tests/basic_test.py
Labels: maintenance

#144 Automated Changelog Entry for 0.13.2 on main
  CHANGELOG.md
Labels: documentation

#146 Test ConPTY backend against pywinpty 2.0.5
  terminado/management.py
Labels: bug

#147 Automated Changelog Entry for 0.13.3 on main
  CHANGELOG.md
Labels: documentation

#148 Add pre-commit
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  LICENSE
  MANIFEST.in
  demos/README.md
  demos/common_demo_stuff.py
  demos/named.py
  demos/single.py
  demos/templates/termpage.html
  demos/templates/uimod.html
  demos/uimod.py
  demos/unique.py
  doc/index.rst
  setup.cfg
  terminado/tests/basic_test.py
Labels: maintenance

#150 Add git-blame-ignore-revs
  .git-blame-ignore-revs
  MANIFEST.in
Labels: maintenance

#152 Clean up pytest and ci matrix
  .github/workflows/check-release.yml
  .github/workflows/test.yml
  pyproject.toml
  setup.cfg
Labels: maintenance
