Repository jupyter/terminado, pull requests merged in 2022-05, with the labels that each got.

#158 Switch to flit build backend
  .flake8
  MANIFEST.in
  pyproject.toml
  setup.cfg
  setup.py
Labels: maintenance

#160 Allow bot PRs to be automatically labeled
  .github/workflows/enforce-label.yml
Labels: maintenance

#161 Handle license file
  pyproject.toml
Labels: maintenance

#165 allow passing extra env vars when a new terminal is created
  terminado/management.py
Labels: enhancement

#166 Switch to hatch backend
  pyproject.toml
Labels: maintenance

#167 Automated Changelog Entry for 0.15.0 on main
  CHANGELOG.md
Labels: documentation
