Repository jupyter/terminado, pull requests merged in 2022-01, with the labels that each got.

#125 Run CI Daily
  .github/workflows/test.yml
Labels: maintenance

#127 Use read_buffer for reconnect and remove preopen_buffer
  terminado/management.py
  terminado/websocket.py
Labels: bug

#128 Automated Changelog Entry for 0.12.2 on main
  CHANGELOG.md
Labels: documentation

#122 Fix terminal output logging type error
  terminado/tests/basic_test.py
  terminado/websocket.py
Labels: bug

#129 Fix formatting of trove classifiers
  setup.cfg
Labels: maintenance

#130 Automated Changelog Entry for 0.12.3 on main
  CHANGELOG.md
Labels: documentation

#131 Fix formatting of trove classifiers again
  setup.cfg
Labels: maintenance

#132 Automated Changelog Entry for 0.12.4 on main
  CHANGELOG.md
Labels: documentation

#133 Fix more setup.cfg formatting
  setup.cfg
Labels: maintenance

#134 Fix even more setup.cfg formatting
  setup.cfg
Labels: maintenance

#136 Add pre_pty_read_hook in pty_read
  terminado/management.py
Labels: enhancement

#137 Officially drop support for python 3.6
  setup.cfg
Labels: maintenance

#138 Automated Changelog Entry for 0.13.0 on main
  CHANGELOG.md
Labels: documentation

#140 python_requires is an option in setup.cfg
  setup.cfg
Labels: maintenance

#141 Automated Changelog Entry for 0.13.1 on main
  CHANGELOG.md
Labels: documentation
